name: synapflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.3
  - pip
  - pip:
      # --- Core PyTorch stack ---
      - torch==2.0.1
      - torchvision==0.15.2
      - torchaudio==2.0.2

      # # --- mmdet + mmcv-full ---
      # - mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch2.0/index.html
      # - mmdet==2.25.0
      # - pycocotools==2.0.6

      # --- ITK ecosystem ---
      - itk==5.4.0
      - itk-core==5.4.0
      - itk-elastix==0.17.3
      - itk-filtering==5.4.0
      - itk-io==5.4.0
      - itk-numerics==5.4.0
      - itk-registration==5.4.0
      - itk-segmentation==5.4.0

      # --- Scientific stack ---
      - matplotlib==3.6.0
      - numpy==1.24.4
      - opencv-python==4.8.1.78
      - pillow==10.1.0
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.9.3
      - tqdm==4.66.2
      - typing-extensions==4.10.0
      - pandas
